language: python
python:
  - "3.7"
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE dep_db_test;'
install:
  - pip install -r requirements.txt
script:
   python -m unittest manage.py











