language: python
python:
  - "3.7"
 before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS dep_db_test;'
install:
  - pip install -r requirements.txt
  services:
  - mysql
script:
  -python manage.py test






